// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package io_github_jason4wy_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Gender               int32    `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	CreatedAt            uint32   `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            uint32   `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *UserInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfo) GetCreatedAt() uint32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserInfo) GetUpdatedAt() uint32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Error) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type QueryRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type QueryResponse struct {
	Code                 uint32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error                *Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *UserInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *QueryResponse) GetData() *UserInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "io.github.jason4wy.srv.user.UserInfo")
	proto.RegisterType((*Error)(nil), "io.github.jason4wy.srv.user.Error")
	proto.RegisterType((*QueryRequest)(nil), "io.github.jason4wy.srv.user.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "io.github.jason4wy.srv.user.QueryResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xb7, 0xae, 0xed, 0xb6, 0x37, 0x07, 0x12, 0x50, 0xcb, 0x44, 0x18, 0x05, 0x71, 0x0a, 0x56,
	0x98, 0x1e, 0xf4, 0x38, 0xd1, 0xc3, 0x8e, 0x06, 0x76, 0x1e, 0xd9, 0xf2, 0xb6, 0x55, 0xb7, 0xa4,
	0x26, 0xe9, 0x64, 0xdf, 0xc4, 0x0f, 0xe5, 0x87, 0x92, 0xa4, 0x99, 0x78, 0x71, 0x78, 0x29, 0xef,
	0xf7, 0x2f, 0x79, 0xef, 0x35, 0x70, 0x54, 0x28, 0x69, 0xe4, 0x4d, 0xa9, 0x51, 0xb9, 0x4f, 0xe6,
	0x30, 0x39, 0xcd, 0x65, 0x36, 0xcf, 0xcd, 0xa2, 0x9c, 0x64, 0xaf, 0x4c, 0x4b, 0x71, 0xf7, 0xb1,
	0xc9, 0xb4, 0x5a, 0x67, 0xd6, 0x92, 0x7e, 0x05, 0xd0, 0x18, 0x69, 0x54, 0x43, 0x31, 0x93, 0xe4,
	0x04, 0xea, 0x96, 0x1c, 0xe7, 0x3c, 0x09, 0xba, 0x41, 0xaf, 0x49, 0x63, 0x0b, 0x87, 0x9c, 0x74,
	0xa0, 0x21, 0xf2, 0xe9, 0x9b, 0x60, 0x2b, 0x4c, 0xf6, 0x9d, 0xf2, 0x83, 0xc9, 0x31, 0xc4, 0x2b,
	0x39, 0xc9, 0x97, 0x98, 0xd4, 0xaa, 0x4c, 0x85, 0xc8, 0x19, 0x00, 0x5b, 0x33, 0xc3, 0xd4, 0xb8,
	0x54, 0xcb, 0x24, 0x74, 0x5a, 0xb3, 0x62, 0x46, 0x6a, 0x69, 0x63, 0x73, 0x14, 0x1c, 0x55, 0x12,
	0x75, 0x83, 0x5e, 0x44, 0x3d, 0xb2, 0xb1, 0xa9, 0x42, 0x66, 0x90, 0x8f, 0x99, 0x49, 0xe2, 0x6e,
	0xd0, 0x6b, 0xd3, 0xa6, 0x67, 0x06, 0xc6, 0xca, 0x65, 0xc1, 0xb7, 0x72, 0xbd, 0x92, 0x3d, 0x33,
	0x30, 0xe9, 0x35, 0x44, 0xcf, 0x4a, 0x49, 0x45, 0x0e, 0xa1, 0xb6, 0xd2, 0x73, 0x3f, 0x86, 0x2d,
	0x09, 0x81, 0x30, 0x17, 0x33, 0xe9, 0xfb, 0x77, 0x75, 0x7a, 0x01, 0x07, 0x2f, 0x25, 0xaa, 0x0d,
	0xc5, 0xf7, 0x12, 0xb5, 0xf9, 0x73, 0x01, 0xe9, 0x67, 0x00, 0x6d, 0xef, 0xd4, 0x85, 0x14, 0x1a,
	0xed, 0x71, 0x53, 0xc9, 0xd1, 0xf9, 0xda, 0xd4, 0xd5, 0xe4, 0x1e, 0x22, 0xb4, 0xb7, 0xbb, 0x3b,
	0x5a, 0xfd, 0x34, 0xdb, 0xb1, 0xf9, 0xcc, 0xf5, 0x49, 0xab, 0x00, 0x79, 0x80, 0x90, 0x33, 0xc3,
	0xdc, 0x0a, 0x5b, 0xfd, 0xf3, 0x9d, 0xc1, 0xed, 0xef, 0xa2, 0x2e, 0xd2, 0x2f, 0x20, 0xb4, 0x0c,
	0x59, 0xf8, 0x0e, 0x2d, 0x78, 0xdc, 0x0c, 0x9f, 0xc8, 0xe5, 0xce, 0x53, 0x7e, 0xcf, 0xdd, 0xb9,
	0xfa, 0x8f, 0xb5, 0x1a, 0x3c, 0xdd, 0x9b, 0xc4, 0xee, 0x5d, 0xdd, 0x7e, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xec, 0xa0, 0x52, 0x90, 0x70, 0x02, 0x00, 0x00,
}
